### ISSUE TITLE
Bad path in manifest

### ISSUE THREAD

**Issue by CianMRoche** [RomeoV/ParticleLife.jl#2]
"path = "/home/romeo/.julia/dev/Agents" in Manifest.toml, means package cant be installed for others as Agents is not stored there. Easiest thing is for you to uninstall and reinstall it through the package manager channels.

**Comment by RomeoV** [comment]
Thanks, I just removed the Manifest file from the repo, which should fix it.
If the issue persists feel free to re-open.

See cfe7f100104c3097321589555d842f0e19832e4d
